# Generated by Django 6.0.6 on 2026-06-18 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
    ]
